
server.address:   localhost
server.port:      8080


spring:
  jpa:
    # API 호출시, SQL 문을 콘솔에 출력한다.
    show-sql:  true

    # DDL 정의시 데이터베이스의 고유 기능을 사용합니다.
    # ex) 테이블 생성, 삭제 등
    spring.jpa.generate-ddl:  true
    hibernate.ddl-auto: create # spring.jpa.properties.hibernate.hbm2ddl.auto 속성과 와 동일

    # MySQL 상세 지정
#    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    # MySQL 을 사용할 것.
#    database:  mysql

  # MySQL 설정
  datasource:
    url:  jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234
    driver-class-name:  org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1